baseURL = "https://wbean1.info/"
languageCode = "en-us"
title = "about wbean1"
theme = "hugo-theme-nix"
publishDir = "docs"

[params]
  GithubID = "wbean1"
  TwitterID = "bbeanis"
  FacebookID = "100000921827528"
  LinkedInID = "wbean1"
  Name = "William Bean"
  HeaderUsername = "root"
  HeaderHostname = "wbean1.info"
  Email = "wbean1@gmail.com"
  About = "I'm a technologist working on Shopify's Production Engineering team.  I curate infrastructure, write package & ship software, and make commerce better for everyone.  Check out my blog, or review the resume!"
  ProfilePicture = "/pic.jpg"

[menu]
  [[menu.header]]
    name = "blog"
    weight = 1
    url = "/posts"
  [[menu.header]]
    name = "resume"
    weight = 0
    url = "/resume.pdf"
